### ISSUE TITLE
"Completed" count broken when using goals

### ISSUE THREAD

**Issue by max11D** [splitrb/split-export#11]
Hi there,

The CSV generator only includes completion count for conversions without any goal. Such is the behavior of `Alternative#completed_count` when called without an argument. See usage at [`/lib/split/export.rb:21`](https://github.com/splitrb/split-export/blob/master/lib/split/export.rb).

The `to_csv` method seems like it should return completion counts for all alternatives. If I understand Split correctly, this would mean summing all goals for each alternative and returning that.

I've attached a screenshot demonstrating the discrepancy between what I'm seeing in my dashboard and what the exporter is returning.

![screenshot from 2016-12-12 15 35 05](https://cloud.githubusercontent.com/assets/6371164/21115756/c27b82a2-c080-11e6-975a-ab7a68f4ba55.png)

**Comment by max11D** [comment]
Conversion Rate and Z-Scores are also broken when using goals. The former is a trivial fix, but the latter will be more involved. I'm working on it on in my own fork (along with another feature I need) so I'll send a pull request when it's done.

**Comment by andrew** [comment]
Thanks for looking into this, I've not used this project in a very long time so feel free to make any changes needed to get it working again
