### ISSUE TITLE
ArgumentError: invalid value for BigDecimal(): "N/A"

### ISSUE THREAD

**Issue by beet** [splitrb/split-export#13]
**Steps to reproduce:**

When attempting to produce an export when a test is present without enough participants to calculate the statistical confidence, exports raise an exception attempting to convert the string "N/A" to a float.

    > csv_data = Split::Export.to_csv
    ArgumentError: invalid value for BigDecimal(): "N/A"
    from /Users/markb/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/split-export-2.0.0/lib/split/export.rb:10:in `initialize'

Could it convert the number to an integer instead of a string to give a value of 0.0?

    [5] pry(main)> BigDecimal.new("NA".to_i).round(2).to_f
    => 0.0

**Comment by andrew** [comment]
@beet maybe we should just rescue and return the string instead?

**Comment by beet** [comment]
@andrew great idea.

I was going to create a fork, but `rake spec` fails with:

    NameError:
      uninitialized constant RSpec::Expectations::MultipleExpectationsNotMetError
    # ./spec/export_spec.rb:3:in `<top (required)>'

Tried upgrading rspec to 3.x, but can't get the tests to run.

**Comment by nhippenmeyer** [comment]
I'm also seeing this exception for tests that have reached statistical significance.  Can a patch be released to fix this bug?

**Comment by andrew** [comment]
Fixed in #18
